language: ruby
cache: bundler
rvm:
  - &latest_ruby 2.7
  - 2.5
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  matrix:
    - JEKYLL_VERSION="~> 3.8"
matrix:
  include:
    - rvm: *latest_ruby
      env: JEKYLL_VERSION="~> 3.8.5"
    - rvm: *latest_ruby
      env: JEKYLL_VERSION="~> 4.0"
before_install:
- gem update --system
before_script: bundle update
script: script/cibuild
notifications:
  email: false
