language: ruby
cache: bundler
rvm:
  - &ruby1 2.7.1
  - &ruby2 2.5.8
matrix:
  include:
    - rvm: *ruby1
      env: JEKYLL_VERSION=">= 4.0.0"
    - rvm: *ruby1
      env: JEKYLL_VERSION="~> 3.8.5"
branches:
  only:
    - master

before_install:
- gem update --system
- gem install bundler
install:
- travis_retry script/bootstrap
script: script/cibuild

notifications:
  irc:
    on_success: change
    on_failure: change
    channels:
    - irc.freenode.org#jekyll
    template:
    - '%{repository}#%{build_number} %{message} %{build_url}'
  email:
    on_success: never
    on_failure: change
