language: ruby
cache: bundler
rvm:
  - 2.4
  - 2.6
  - jruby-9.2.5.0
gemfile:
  - Gemfile
  - Gemfile-jruby

matrix:
  exclude:
    - rvm: jruby-9.2.5.0
      gemfile: Gemfile
    - rvm: 2.4
      gemfile: Gemfile-jruby
    - rvm: 2.6
      gemfile: Gemfile-jruby

notifications:
  irc:
    on_success: change
    on_failure: change
    channels:
    - irc.freenode.org#jekyll
    template:
    - '%{repository}#%{build_number} %{message} %{build_url}'
  email:
    on_success: never
    on_failure: change

services:
  - redis-server
