curl "https///api.github.com/orgs/jekyll/repos?per_page=1000" | grep -o 'git clone https://[^"]*' | xargs -L1 git clone

git clone https://github.com/jekyll/jekyll.git
git clone https://github.com/jekyll/jekyll-import.git
git clone https://github.com/jekyll/test-site.git
git clone https://github.com/jekyll/directory.git
git clone https://github.com/jekyll/brand.git
git clone https://github.com/jekyll/jekyll-test-gem-plugin.git
git clone https://github.com/jekyll/mercenary.git
git clone https://github.com/jekyll/jekyll-test-plugin-malicious.git
git clone https://github.com/jekyll/hyde.git
git clone https://github.com/jekyll/jekyll-redirect-from.git
git clone https://github.com/jekyll/jekyll-test.git
git clone https://github.com/jekyll/jemoji.git
git clone https://github.com/jekyll/jekyll-mentions.git
git clone https://github.com/jekyll/screencast.git
git clone https://github.com/jekyll/jekyll-coffeescript.git
git clone https://github.com/jekyll/jekyll-sass-converter.git
git clone https://github.com/jekyll/hubot-pr-status.git
git clone https://github.com/jekyll/atom-jekyll.git
git clone https://github.com/jekyll/jekyll-sitemap.git
git clone https://github.com/jekyll/jekyll-help.git
git clone https://github.com/jekyll/themes-site.git
git clone https://github.com/jekyll/jekyll-compose.git
git clone https://github.com/jekyll/jekyll-paginate.git
git clone https://github.com/jekyll/jekyll-gist.git
git clone https://github.com/jekyll/mojobot.git
git clone https://github.com/jekyll/jekyll-opal.git
git clone https://github.com/jekyll/cases.git
git clone https://github.com/jekyll/jekyll-watch.git
git clone https://github.com/jekyll/classifier-reborn.git
git clone https://github.com/jekyll/jekyll-archives.git
git clone https://github.com/jekyll/profiling.git
git clone https://github.com/jekyll/github-metadata.git
git clone https://github.com/jekyll/omnibus-jekyll.git
git clone https://github.com/jekyll/example.git
git clone https://github.com/jekyll/jekyll-docs.git
git clone https://github.com/jekyll/jekyll-textile-converter.git
git clone https://github.com/jekyll/jekyll-feed.git
git clone https://github.com/jekyll/jekyll-seo-tag.git
git clone https://github.com/jekyll/benchmarking.git
git clone https://github.com/jekyll/jekyll-commonmark.git
git clone https://github.com/jekyll/dashboard.git
git clone https://github.com/jekyll/teams.git
git clone https://github.com/jekyll/jekyll-admin.git
git clone https://github.com/jekyll/minima.git
git clone https://github.com/jekyll/acceptance.git
git clone https://github.com/jekyll/jekyll-test-theme-malicious.git
git clone https://github.com/jekyll/dns.git
git clone https://github.com/jekyll/Utterson.git
git clone https://github.com/jekyll/rubocop-jekyll.git
git clone https://github.com/jekyll/common-theme.git
git clone https://github.com/jekyll/carbon-copy-content.git
git clone https://github.com/jekyll/.github.git
git clone https://github.com/jekyll/jekyllbot.git
