language: ruby
cache: bundler
rvm:
  - &latest_ruby 2.7
  - 2.5
git:
  depth: 3

# we need a more recent cmake than travis/linux provides (at least 2.8.9):
addons:
  apt:
    sources:
      - kalakris-cmake
    packages:
      - cmake

before_install:
  - gem update --system
  - gem install bundler
before_script: bundle update
script: script/cibuild

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  matrix:
    - JEKYLL_VERSION="~> 3.8"

matrix:
  include:
    - rvm: *latest_ruby
      env: JEKYLL_VERSION="~> 3.8.5"
    - rvm: *latest_ruby
      env: JEKYLL_VERSION=">= 4.0.0"
