language: ruby
cache: bundler
rvm:
  - &latest_ruby 2.7
  - 2.5

script : script/cibuild

branches:
  only:
    - master
env:
  matrix:
  - JEKYLL_VERSION="~> 3.8"
matrix:
  include:
    - # GitHub Pages
      rvm: 2.5.3
      env: JEKYLL_VERSION="~> 3.8.5"
    - rvm: *latest_ruby
      env: JEKYLL_VERSION="~> 4.0"

notifications:
  email: false
