language: ruby
cache: bundler
rvm:
- 2.6
- 2.4

matrix:
  include:
    -
      rvm: 1.9
      env: JEKYLL_VERSION=2.0

script : script/cibuild
branches:
  only:
  - master

notifications:
  email: false

env:
  - JEKYLL_VERSION=3.0
  - JEKYLL_VERSION=2.0
