dist: bionic
cache: bundler
language: ruby
rvm:
  - 2.7
  - 2.5
env:
  matrix:
    - JEKYLL_VERSION=4.0
branches:
  only:
    - master
before_install:
- gem update --system
script: script/cibuild
notifications:
  irc:
    on_success: change
    on_failure: change
    channels:
    - irc.freenode.org#jekyll
    template:
    - '%{repository}#%{build_number} %{message} %{build_url}'
  email:
    on_success: never
    on_failure: change
